### ISSUE TITLE
Project not working in Unity 2019.1.11f1

### ISSUE THREAD

**Issue by shayanahmad101** [BerkeCagkanToptas/OSM-City-Engine#2]
I tried opening the project in Unity 2019.1.11f1 but there were some packages that are not being used for this version of Unity. Unity itself tried to resolve those packages to work but there are still 2 errors:

1. Assets\Scripts\Utils\UniZip.cs(5,7): error CS0246: The type or namespace name 'Ionic' could not be found.
2. Assets\Scripts\Utils\LoadExternalOBJ.cs(12,9): error CS0246: The type or namespace name 'ObjReader' could not be found.

Other than these errors the scripts attached to the objects are missing.

You have done some great work here. Kindly help in resolving this issue.
